### PR TITLE
 chore: get rid of twind, use tailwindcss proper 

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Comment by notmandatory** [comment]
Thank you 🙏 until I saw this project I didn't know tailwinds could parse my maud .rs files!

**Comment by dpc** [comment]
Kudos to the person that told me about it that I can't find the post to credit. I didn't know myself. :)

**Comment by dpc** [comment]
@notmandatory BTW. If you're using this repo as a source of inspiration, then in another project I did bunch of stuff even better (IMO) than here. Eg. a peroper build.rs for tailwind https://github.com/rustshop/perfit/blob/master/build.rs

**Comment by notmandatory** [comment]
Amazing thanks, I was also thinking about how to run the tailwindscss in the buid.rs and you've already done it! I'll check out the rest of your project too, probably other bits I can use.

**Pull request merged**
